### PR TITLE
feat: add css grid properties

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
Hi 👋🏻
Thank you for this amazing library. I've decided to give something back and I've created this small PR.

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @krzysztofzuraw and thanks for the PR!

I am actually looking for someone to take over the project, cause for me this was just an idea I put out. I do not really have time to follow it up 😄 

If you wanna run the project I can transfer the repo and NPM package to your account 😄

**Comment by themsammy** [comment]
Hello @krzysztofzuraw and thank you for the great PR!
If you are interested in being a collaborator I can send an invite!

**Comment by krzysztofzuraw** [comment]
sure 👍  I will be happy to help 😃

**Comment by krzysztofzuraw** [comment]
ping @themsammy 😄

**Comment by themsammy** [comment]
Great, I sent you the invite :smiley:

**Pull request merged**
