### PR TITLE
Add missing border, transitions and typography classes

### PR DESCRIPTION
**Pull request by themsammy**

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @themsammy, 

This are great contributions! You wanna take over the repo and npm package? 

I only put this out as an idea and was happy to see that it made a ton of sense for many people, but my plate is a bit full to follow it up 😄

**Comment by themsammy** [comment]
Thank you @christianalfoni 😄
I really like this project and I would love to take over it with pleasure.

**Comment by christianalfoni** [comment]
Great! If you could delete your fork or rename it to something else I can transfer it 😄

**Comment by themsammy** [comment]
@christianalfoni done!

**Comment by christianalfoni** [comment]
You also need a user on NPM to publish the package 😄

**Comment by themsammy** [comment]
Yes 😅, its here [themsammy](https://www.npmjs.com/~themsammy)

**Comment by themsammy** [comment]
Could you please transfer the NPM package to my user, @christianalfoni 😃

**Comment by christianalfoni** [comment]
Okay, great! Let me know if you have any questions related to Git or Npm, happy to help 😄

**Pull request closed without merging**
